apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-ingress
spec:
  rules:
    - host: atlas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80